<a href="https://colab.research.google.com/github/JasonCha7/pyhton/blob/main/class_11_2024149753_%EC%B0%A8%EA%B2%BD%ED%9B%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

Array fundamentals

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a[0]

np.int64(1)

In [5]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [6]:
a[:3]

array([10,  2,  3])

In [7]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [8]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[1, 3]

np.int64(8)

Array attributes

In [10]:
a.ndim

2

In [11]:
a.shape
len(a.shape) == a.ndim

True

In [12]:
a.size
import math
a.size == math.prod(a.shape)

True

In [13]:
a.dtype

dtype('int64')

How to create a basic array

In [14]:
np.zeros(2)

array([0., 0.])

In [15]:
np.ones(2)

array([1., 1.])

In [16]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [17]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [20]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

Adding, removing, and sorting elements

In [22]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [23]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [25]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [27]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

How do you know the shape and size of an array?

In [28]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [29]:
array_example.ndim

3

In [30]:
array_example.size

24

In [31]:
array_example.shape

(3, 2, 4)

Can you reshape an array?

In [42]:
a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

np.reshape(a, shape=(1, 6), order='C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


TypeError: reshape() got an unexpected keyword argument 'shape'

In [43]:

np.reshape(a, (1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [44]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [45]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [46]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [47]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [49]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [50]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

Indexing and slicing

In [51]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [52]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [53]:
print(a[a < 5])

[1 2 3 4]


In [54]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [55]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [56]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [57]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [58]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [59]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [60]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [61]:
print(a[b])

[1 2 3 4]


In [62]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


ow to create an array from existing data

In [63]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [65]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [66]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [67]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [68]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [70]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [71]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [72]:
b1 = a[0, :]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
b2 = a.copy()

Basic array operations

In [74]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [75]:
data - ones
data * data
data / data

array([1., 1.])

In [76]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [77]:
b = np.array([[1, 1], [2, 2]])

In [78]:
b.sum(axis=0)

array([3, 3])

In [79]:
b.sum(axis=1)

array([2, 4])

Broadcasting

In [80]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

More useful array operations

In [81]:
data.max()
data.min()
data.sum()

np.float64(3.0)

In [82]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [83]:
a.sum()

np.float64(4.8595784)

In [84]:
a.min()

np.float64(0.05093587)

In [85]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

Creating matrices

In [86]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
data[0, 1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [88]:
data.max()
data.min()
data.sum()

np.int64(21)

In [89]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)
data.max(axis=1)

array([2, 5, 6])

In [90]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [91]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [92]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [93]:
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.82464731, 0.36183429, 0.89070795])

In [94]:
np.ones((3, 2))
np.zeros((3, 2))
rng.random((3, 2))

array([[0.01018106, 0.14815373],
       [0.03737213, 0.54545452],
       [0.54766117, 0.02704537]])

Generating random numbers

In [95]:
rng.integers(5, size=(2, 4))

array([[0, 3, 2, 4],
       [4, 1, 4, 3]])

How to get unique items and counts

In [96]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [97]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [98]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [99]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [100]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [101]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [102]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [103]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


Transposing and reshaping a matrix

In [104]:
data.reshape(2, 3)
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [107]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [108]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

How to reverse an array

In [109]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
reversed_arr = np.flip(arr)

In [111]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [112]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [113]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [114]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [115]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [116]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [117]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [118]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9  2 11 12]]


Reshaping and flattening multidimensional arrays

In [119]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [120]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [121]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [122]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
